### ISSUE TITLE
Add a new task list

### ISSUE THREAD

**Issue by marbetschar** [elementary/tasks#107]
It should be possible to add a new task list. Something like the following:

![mac_reminders](https://user-images.githubusercontent.com/392542/79066744-9db70500-7cba-11ea-9e02-90abc74a03c2.jpg)

**Comment by rectangular** [comment]
![tasks-add-list](https://user-images.githubusercontent.com/354758/80266881-8af9e400-865b-11ea-854c-54a263b1349a.png)

My preference would be to use a fairly standard button.

Here's my thinking:

- It shouldn't have color that could complete with list or item colors.
- It should have defined bounds to help indicate hit area.
- It should be able to sit on top of a scrollable list of uh… lists without visual collision.
- If it has a button shape, I don't think it needs an icon. I'm not sure what a plus icon would additionally communicate.
- Additionally, I'm not sure it needs an icon because it will be infrequently used and the function won't need to be quickly parsed. An icon might only add noise to compete with content (How many lists does everyone have or use regularly? I am at less than 10 on all my devices).

I'm not sure if there's precedent, but it might be nice to indicate the shortcut for this action on hover.

![tasks-add-list-hover](https://user-images.githubusercontent.com/354758/80267693-9a7b2c00-865f-11ea-8fb9-64896423447f.png)

I know I'm butting into this conversation (Hi! I'm Geof 👋 ), so I'm not sure if a borderless button has already been decided on. If so, here's how I think we could handle that:

![tasks-add-list-icon](https://user-images.githubusercontent.com/354758/80267737-c8f90700-865f-11ea-9f49-2c9c6be17e7a.png)

I used `actions/16/list-add.svg`.

If we use a borderless icon, I think the alignment of the list-add icon with the list color circle is important. I also think that the Add List label should be aligned with the list labels.

That is pictured here:

![tasks-add-list-icon-alignment](https://user-images.githubusercontent.com/354758/80267803-35740600-8660-11ea-9f01-a7b84198e7f6.png)

Think this would work?

**Comment by marbetschar** [comment]
@rectangular thanks for your input! I understand the reasoning for the standard button. However, I'm not quite sure I like it visually - for me, the button grabs quite a lot of attention to the lower left corner.

I think @danrabbit experimented with a toolbar at the bottom in the `add-task-list` branch, similar to the one pictured below. However, I don't know what the current state of the work is there.

![Screenshot from 2020-04-27 08-13-52](https://user-images.githubusercontent.com/392542/80339610-548cb680-885f-11ea-81c3-c568df3ae0a7.png)

**Comment by rectangular** [comment]
@marbetschar Thanks for the feedback! I can definitely understand the reaction to the visual weight of a standard button. Maybe we could strike a nice balance with a borderless icon+text button (i think this would be a common scenario of # of lists and variety of colors):

![tasks-add-list-icon-short-list](https://user-images.githubusercontent.com/354758/80399072-d8ea3400-8875-11ea-94ae-7423485d6158.png)

At least until there's enough task lists to warrant the button being boxed in to prevent visual collision:

![tasks-add-list-icon-long-list](https://user-images.githubusercontent.com/354758/80399087-e0114200-8875-11ea-8f40-4a9098555d83.png)

We could still disclose what the keyboard shortcut is to the user on hover:

![tasks-add-list-icon-long-list-hover-keys](https://user-images.githubusercontent.com/354758/80399186-0636e200-8876-11ea-9d41-d0e4628b7a67.png)

Visually imitating keys around the shortcut text might also grab too much visual attention, maybe text would suffice?

![tasks-add-list-icon-long-list-hover-text](https://user-images.githubusercontent.com/354758/80399337-44cc9c80-8876-11ea-8a3e-79970dbff925.png)

Are we hoping to also include a `Delete List` button next to the `Add List` button as well?

**Comment by marbetschar** [comment]
I really like your last approach 💪️

Delete list is already taken care of in the list settings:

![image](https://user-images.githubusercontent.com/392542/80400153-b0385d80-88ba-11ea-8eef-d385a4261275.png)

**Comment by marbetschar** [comment]
Closing because this has been implemented.
