### ISSUE TITLE
Duplicated tasks in Scheduled view when changing color of the task list

### ISSUE THREAD

**Issue by lenemter** [elementary/tasks#359]
### What Happened?

Duplicated tasks in Scheduled view when changing color of the task list.

![image](https://github.com/elementary/tasks/assets/80143868/90dbbd1d-10eb-4cbe-a7f5-c95f12aa4f78)

### Steps to Reproduce

1. Open task list with tasks with due dates
2. Change its color
3. Open Scheduled view

### Expected Behavior

No duplicated tasks.

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by Claudio-code** [comment]
Analyzing the code it seems that this error happens because the ScheduledTaskListBox class has the signal methods task_list_added, task_list_modified and task_list_removed connected with your implementation and it shouldn't. TaskModel should be unique class to control state of tasks to avoid to connectors throw updated same event.

**Comment by Claudio-code** [comment]
I managed to find Tasks.Widgets.TaskRow but it has the source with the hash and uid different from what comes by parameter in the function so the validation still wouldn't work

![image](https://github.com/elementary/tasks/assets/42524939/034fd7b6-3c18-4bfd-bdb5-c6d2f9915f9b)

**Comment by Claudio-code** [comment]
if you remove the right TaskRow it stops duplicating anymore I can't find how to compare the TaskRow.source with the source that comes as a parameter

**Comment by Claudio-code** [comment]
i think found solution if change get_children () to task_list.get_children () it method can remove repeated items
